
export const users = [
  { "id": 1, "name": "Trefor Balentyne", "email": "tbalentyne0@twitpic.com", "cpf": "532-51-0651", "address": "69093 Jay Point", "userType": "cliente", "userOrders": [1, 2] },
  { "id": 2, "name": "Lucina Ovenell", "email": "lovenell1@hp.com", "cpf": "247-94-2389", "address": "115 Armistice Center", "userType": "client", "userOrders": [] },
  { "id": 3, "name": "Barnie Hoyland", "email": "bhoyland2@macromedia.com", "cpf": "315-35-7863", "address": "65610 Coolidge Junction", "userType": "client", "userOrders": [] },
  { "id": 4, "name": "Leandra Coslett", "email": "lcoslett3@parallels.com", "cpf": "806-48-1053", "address": "919 7th Drive", "userType": "admin", "userOrders": [] },
  { "id": 5, "name": "Filberto Pleaden", "email": "fpleaden4@trellian.com", "cpf": "746-48-1758", "address": "7 Sunnyside Trail", "userType": "client", "userOrders": [] },
  { "id": 6, "name": "Ruthy Tretwell", "email": "rtretwell5@comsenz.com", "cpf": "882-78-6865", "address": "268 Jay Junction", "userType": "client", "userOrders": [] },
  { "id": 7, "name": "Ambrosi Sparshutt", "email": "asparshutt6@rambler.ru", "cpf": "589-74-1802", "address": "76 Leroy Center", "userType": "client", "userOrders": [] },
  { "id": 8, "name": "Hakeem Mc Faul", "email": "hmc7@mapy.cz", "cpf": "283-08-0305", "address": "479 Sullivan Crossing", "userType": "client", "userOrders": [] },
  { "id": 9, "name": "Joel Bromehed", "email": "jbromehed8@etsy.com", "cpf": "573-72-4332", "address": "7 Ruskin Crossing", "userType": "client", "userOrders": [] },
  { "id": 10, "name": "Charmine Johanssen", "email": "cjohanssen9@about.com", "cpf": "447-93-6389", "address": "4506 Charing Cross Hill", "userType": "admin", "userOrders": [] },
  { "id": 11, "name": "Dennis Cranston", "email": "dcranstona@51.la", "cpf": "532-83-4287", "address": "4 Pawling Park", "userType": "client", "userOrders": [] },
  { "id": 12, "name": "Aron Ionnisian", "email": "aionnisianb@zdnet.com", "cpf": "487-61-3791", "address": "362 Northview Place", "userType": "client", "userOrders": [] },
  { "id": 13, "name": "Flin De Giorgio", "email": "fdec@baidu.com", "cpf": "329-20-4866", "address": "9740 Jackson Court", "userType": "client", "userOrders": [] },
  { "id": 14, "name": "Wang Turl", "email": "wturld@nsw.gov.au", "cpf": "557-42-6814", "address": "17808 Buell Street", "userType": "client", "userOrders": [] },
  { "id": 15, "name": "Lammond Stockford", "email": "lstockforde@weibo.com", "cpf": "207-24-7392", "address": "313 Judy Avenue", "userType": "admin", "userOrders": [] },
  { "id": 16, "name": "Chastity Parris", "email": "cparrisf@narod.ru", "cpf": "820-53-5505", "address": "7 Granby Parkway", "userType": "client", "userOrders": [] },
  { "id": 17, "name": "Sidonia de Amaya", "email": "sdeg@moonfruit.com", "cpf": "178-68-6085", "address": "5 Buell Circle", "userType": "client", "userOrders": [] },
  { "id": 18, "name": "Hal Denyer", "email": "hdenyerh@arstechnica.com", "cpf": "340-01-9660", "address": "9 2nd Road", "userType": "client", "userOrders": [] },
  { "id": 19, "name": "Sascha Salerg", "email": "ssalergi@nhs.uk", "cpf": "233-60-1959", "address": "9068 Esch Lane", "userType": "client", "userOrders": [] },
  { "id": 20, "name": "Kasey Cordall", "email": "kcordallj@hatena.ne.jp", "cpf": "525-06-9033", "address": "98 Mcguire Street", "userType": "client", "userOrders": [] },
  { "id": 21, "name": "Prissie O'Carran", "email": "pocarrank@stumbleupon.com", "cpf": "122-57-6835", "address": "649 Lillian Street", "userType": "client", "userOrders": [] },
  { "id": 22, "name": "Karlik Petrasso", "email": "kpetrassol@delicious.com", "cpf": "301-07-5820", "address": "84849 Scott Alley", "userType": "client", "userOrders": [] },
  { "id": 23, "name": "Pierre Martin", "email": "pmartinm@nyu.edu", "cpf": "472-63-9021", "address": "9 Graceland Way", "userType": "client", "userOrders": [] },
  { "id": 24, "name": "Boot Mandel", "email": "bmandeln@ocn.ne.jp", "cpf": "654-14-3290", "address": "1034 Westerfield Drive", "userType": "admin", "userOrders": [] },
  { "id": 25, "name": "Dredi Wagstaffe", "email": "dwagstaffeo@bigcartel.com", "cpf": "722-65-0839", "address": "30872 Doe Crossing Terrace", "userType": "client", "userOrders": [] },
  { "id": 26, "name": "Alfons MacSkeagan", "email": "amacskeaganp@indiegogo.com", "cpf": "895-84-1946", "address": "558 Hintze Avenue", "userType": "client", "userOrders": [] },
  { "id": 27, "name": "Ingeberg Celli", "email": "icelliq@msu.edu", "cpf": "647-02-3287", "address": "8 Arrowood Way", "userType": "client", "userOrders": [] },
  { "id": 28, "name": "Valencia Ansley", "email": "vansleyr@blogger.com", "cpf": "576-84-1311", "address": "61 Elgar Drive", "userType": "admin", "userOrders": [] },
  { "id": 29, "name": "Ailene Alforde", "email": "aalfordes@pinterest.com", "cpf": "868-70-6805", "address": "834 Green Ridge Place", "userType": "client", "userOrders": [] },
  { "id": 30, "name": "Adorne Peatt", "email": "apeattt@cloudflare.com", "cpf": "662-49-8184", "address": "9835 Jenifer Alley", "userType": "client", "userOrders": [] },
  { "id": 31, "name": "Joli Derbyshire", "email": "jderbyshireu@imgur.com", "cpf": "213-48-0848", "address": "04022 Mcbride Drive", "userType": "client", "userOrders": [] },
  { "id": 32, "name": "Aloisia Sopper", "email": "asopperv@myspace.com", "cpf": "591-77-5569", "address": "9 4th Trail", "userType": "client", "userOrders": [] },
  { "id": 33, "name": "Dorothy Wombwell", "email": "dwombwellw@cmu.edu", "cpf": "629-72-9406", "address": "27 Fuller Pass", "userType": "client", "userOrders": [] },
  { "id": 34, "name": "Lorrie Hallagan", "email": "lhallaganx@ed.gov", "cpf": "627-07-5077", "address": "7886 Farmco Drive", "userType": "client", "userOrders": [] },
  { "id": 35, "name": "Herta Emloch", "email": "hemlochy@smh.com.au", "cpf": "646-41-2732", "address": "5515 Talmadge Street", "userType": "client", "userOrders": [] },
  { "id": 36, "name": "Ellswerth Coskerry", "email": "ecoskerryz@berkeley.edu", "cpf": "573-25-7463", "address": "433 Briar Crest Crossing", "userType": "client", "userOrders": [] },
  { "id": 37, "name": "Adiana Costelow", "email": "acostelow10@symantec.com", "cpf": "678-65-8728", "address": "1319 Oak Center", "userType": "client", "userOrders": [] },
  { "id": 38, "name": "Lynnet Balint", "email": "lbalint11@aboutads.info", "cpf": "103-23-2186", "address": "5252 Old Shore Trail", "userType": "client", "userOrders": [] },
  { "id": 39, "name": "Fletcher Macveigh", "email": "fmacveigh12@theatlantic.com", "cpf": "245-57-5811", "address": "23205 Pleasure Junction", "userType": "client", "userOrders": [] },
  { "id": 40, "name": "Marmaduke Merrien", "email": "mmerrien13@friendfeed.com", "cpf": "310-69-9499", "address": "7183 Coleman Place", "userType": "client", "userOrders": [] },
  { "id": 41, "name": "Dorena Kleiner", "email": "dkleiner14@si.edu", "cpf": "418-31-0415", "address": "4 Macpherson Drive", "userType": "client", "userOrders": [] },
  { "id": 42, "name": "Nico Dymock", "email": "ndymock15@newyorker.com", "cpf": "273-66-0197", "address": "070 Sunnyside Court", "userType": "admin", "userOrders": [] },
  { "id": 43, "name": "Krissie Shawl", "email": "kshawl16@sciencedaily.com", "cpf": "853-47-8571", "address": "51415 Gina Circle", "userType": "client", "userOrders": [] },
  { "id": 44, "name": "Zahara McCotter", "email": "zmccotter17@mashable.com", "cpf": "347-62-9020", "address": "122 Emmet Terrace", "userType": "client", "userOrders": [] },
  { "id": 45, "name": "Dan Yakebovitch", "email": "dyakebovitch18@newyorker.com", "cpf": "131-28-0633", "address": "01426 Laurel Place", "userType": "client", "userOrders": [] },
  { "id": 46, "name": "Margery Zorzin", "email": "mzorzin19@imgur.com", "cpf": "437-39-7986", "address": "1 Reinke Terrace", "userType": "client", "userOrders": [] },
  { "id": 47, "name": "Ban Dumper", "email": "bdumper1a@blinklist.com", "cpf": "636-38-9957", "address": "12576 Dahle Center", "userType": "client", "userOrders": [] },
  { "id": 48, "name": "Eugenius Placido", "email": "eplacido1b@nasa.gov", "cpf": "375-63-6879", "address": "128 Huxley Park", "userType": "client", "userOrders": [] },
  { "id": 49, "name": "Rog Gouinlock", "email": "rgouinlock1c@seattletimes.com", "cpf": "257-66-1048", "address": "72833 Eagan Plaza", "userType": "client", "userOrders": [] },
  { "id": 50, "name": "Fleur Sharpless", "email": "fsharpless1d@163.com", "cpf": "819-15-5225", "address": "7020 Maple Wood Road", "userType": "client", "userOrders": [] }
];

export const products = [
  { "id": 1, "name": "Whiskey Woodford Reserve 750ml", "category": "Tennessee Whiskey", "img": "", "price": 185.91, "description": "Woodford Reserve é um luxuoso bourbon, cuidadosamente produzido à mão em pequenos lotes na Woodford Reserve Distillery. Tradicional desde 1812, é a destilaria mais antiga dos Estados Unidos. Triplamente destilada e envelhecida sob medida ao longo do tempo em barris de carvalho branco americano. É o unico bourbon do mundo a ter barris criados especificamente para sua produção. O mashbill para Woodford Reserve apresenta uma elevada porcentagem de centeio: 72% do milho, 18% de centeio e 10% de malte." },
  { "id": 2, "name": "Whisky Suntory Hibiki Harmony 700ml", "category": "Whisky Japonês", "img": "", "price": 632.31, "description": "Luminoso, delicado, de uma transparência que revela complexidade. O Whisky Hibiki Harmony é uma bebida leve com notas de cascas de laranja e chocolate branco que ajuda a torná-lo um whisky sedutor. Ele é formado por grãos e maltes do Japão que ajuda a fazer dele uma bebida que representa estações do país." },
  { "id": 3, "name": "Bourbon Maker's Mark 700ml", "category": "Bourbon Whiskey", "img": "", "price": 139.90, "description": "O Bourbon Maker's Mark é uma bebida produzida em Loretto, Kentucky, nos Estados Unidos. É conhecido pelo seu processo de produção, que inclui a utilização de milho vermelho, cevada maltada e centeio em sua composição, além de ser envelhecido em barris de carvalho branco americano por seis anos." },
  { "id": 4, "name": "Bourbon Wild Turkey 101 1L", "category": "Bourbon Whiskey", "img": "", "price": 219.90, "description": "O Bourbon Wild Turkey 101 é uma bebida produzida em Lawrenceburg, Kentucky, nos Estados Unidos. É conhecido pela sua alta graduação alcoólica, que chega a 50,5% em volume, e pelo seu sabor rico em notas de baunilha, caramelo e especiarias." },
  { "id": 5, "name": "Rye Whiskey Bulleit 750ml", "category": "Rye", "img": "", "price": 149.90, "description": "O Rye Whiskey Bulleit é uma bebida produzida em Lawrenceburg, Kentucky, nos Estados Unidos. É conhecido pelo seu sabor marcante de centeio, que lhe confere notas picantes e terrosas, além de um final seco e persistente. É envelhecido por no mínimo quatro anos em barris de carvalho branco americano." },
];

export const orders = [
  { "id": 1, "name": "Trefor Balentyne", "productsList": [{ "productID": 1, "quantity": 2 }, { "productID": 2, "quantity": 2 }], "totalPrice": 1004.13, "orderDate": "17-12-2022" },
  { "id": 2, "name": "Trefor Balentyne", "productsList": [{ "productID": 1, "quantity": 1 }, { "productID": 2, "quantity": 2 }], "totalPrice": 1450.53, "orderDate": "30-07-2022" },
]

export const categories = [
  { "id": 1, "name": "Tennessee Whiskey" },
  { "id": 2, "name": "Whisky Japonês" },
];